name: Fly Deploy
on:
    push:
        branches:
        - main
jobs:
    release-notes:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v5
              with:
                python-version: '3.12'
                cache: 'pip'
            - name: Build Pydoc-Markdown
              run: |
                pip install pydoc-markdown
                mkdir -p $(pwd)/tmp_docs
                pydoc-markdown -I $(pwd)/chatbot/ --render-toc > $(pwd)/tmp_docs/README.md
            - name: Upload Release Notes to Wiki
              uses: docker://decathlon/wiki-page-creator-action:latest
              env:
                ACTION_MAIL: chenmengyang_2016@hotmail.com
                ACTION_NAME: SuperChenSSS
                GH_PAT: ${{ secrets.GIT_TOKEN }}
                MD_FOLDER: tmp_docs
                OWNER: SuperChenSSS
                REPO_NAME: comp7940-lab

    deploy:
        name: Deploy app
        runs-on: ubuntu-latest
        concurrency: deploy-group
        env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
            APP: ${{ vars.APP_NAME}}
        steps:
            - uses: actions/checkout@v3
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - name: Deploy to Fly
              run: flyctl deploy --remote-only --no-cache
              working-directory: ./chatbot
            - name: Limit to 1 VM
              run: flyctl scale count 1 -a $APP